[theme]
primaryColor = "#5e12ab"
textColor = "white"
backgroundColor = "#151515"
buttonRadius = "0.5rem"
secondaryBackgroundColor = "#23233a"

[theme.sidebar]
backgroundColor = "#1e1d20"
primaryColor = "#8a12fa"

[server]
enableStaticServing = true